import "./globals.css";

import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { ResponsiveWrapper } from "@/components/ResponsiveWrapper";
import { ThemeProviders } from "@/context/ThemeContext";
import { cn } from "@/lib/utils";

const poppins = Poppins({ weight: "500", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body className={cn("transition-colors duration-50 ", poppins.className)}>
        <ThemeProviders>
          <ResponsiveWrapper>{children}</ResponsiveWrapper>
        </ThemeProviders>
      </body>
    </html>
  );
}
