import './globals.css';

import type { Metadata } from 'next';
import NavBar from '@/components/navbar/NavBar';
import { Poppins } from 'next/font/google';
import { ThemeProviders } from '@/context/ThemeContext';
import { cn } from '@/lib/utils';

const poppins = Poppins({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className=''>
      <body className={cn('transition-colors duration-50 home-bg', poppins.className)}>
          <ThemeProviders>
            <div className='fixed w-full px-3 py-3 md:px-20 bg-primary dark:bg-primary-foreground text-primary-foreground dark:text-primary '>
              <NavBar />
            </div>
            <div className='w-full min-h-full'>{children}</div>
          </ThemeProviders>
      </body>
    </html>
  );
}
