import './globals.css';

import { DM_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import { ResponsiveWrapper } from '@/components/ResponsiveWrapper';
import { ThemeProviders } from '@/context/ThemeContext';
import { cn } from '@/lib/utils';

const poppins = DM_Sans({ weight: '500', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="" suppressHydrationWarning>
      <body className={cn('transition-colors duration-50 ', poppins.className)}>
        <ThemeProviders>
          <ResponsiveWrapper>{children}</ResponsiveWrapper>
        </ThemeProviders>
      </body>
    </html>
  );
}
